name: Test Example

on:
  workflow_dispatch:
    inputs:
      descriptionAI:
        description: 'Do you want AI to generate description for the test run?'
        required: true
        type: choice
        options:
          - no
          - yes
jobs:
  test-execution:
    name: Execute Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          cache: 'maven'

      - name: Set up Maven Authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          echo "<settings><servers><server><id>github</id><username>MisterAiAutomation</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Set Git Remote URL
        run: |
          git remote set-url origin https://MisterAiAutomation:${{ secrets.GIT_TOKEN }}@github.com/ai-automation-testing-team/automation-testing-project.git          

      - name: Run initial setup tests from maven
        run: |
          mvn clean test '-Dsurefire.suiteXmlFiles=src/test/resources/testSuite.xml' '-Dbrowser.type=chrome-headless' '-Ddriver.version=116.0.5845.96' '-Dgit.token=${{ secrets.GIT_TOKEN }}' '-Dai.token=${{ secrets.AI_TOKEN }}'

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'Test report'
          state: 'success'
          target_url: https://ai-automation-testing-team.github.io/automation-testing-project/${{ github.run_number }}/

      - name: Test Report in summary
        if: always()
        run: |
          echo '### Test Report' >> $GITHUB_STEP_SUMMARY
          echo '[Results](https://ai-automation-testing-team.github.io/automation-testing-project/${{ github.run_number }}/ "Allure Report")' >> $GITHUB_STEP_SUMMARY